### ISSUE TITLE
Can't Check-out files when folder has accent.

### ISSUE THREAD

**Issue by ojusto** [chrishasz/spgo#98] opened 2019-09-19 18:42 UTC
Hi, 

i`m having a issue to check-out files when folder as accent. To check-in , save when checked-out and populate workspace all works fine.

In the error message , i see the character with accent has replaced by a stranger character.

One workaround to this is check-out file in SPD.

**Comment by chrishasz** [comment] 2019-09-22 15:49
Hello @ojusto - Thank you for reporting this issue. I think this may be the root cause to a few of the other check-in/check-out issues that others have reported.

Can you do me a favor and post just the name of the folder , with accent character, so that I can replicate and fix your exact issue? I don't need server name, or any other private details, just the folder name.

**Comment by ojusto** [comment] 2019-09-23 13:58
Hi @chrishasz ,
Sure , the folder name is "Tributário". If helps , the image below show the error message

![image](https://user-images.githubusercontent.com/55556542/65431997-cba52c80-ddf0-11e9-8962-9694e1edc1e4.png)

i will try debug your code to see if i can help with something .

**Comment by chrishasz** [comment] 2019-10-08 15:12
Hello @ojusto 

I have resolved this issue in my local build and will be releasing an update to the VS Marketplace this week. Thank for your help in resolving!

**Comment by ojusto** [comment] 2019-10-08 16:28
Hi @chrishasz , 
I`m very happy with this news. Thanks for your job!

**Comment by chrishasz** [comment] 2019-10-10 18:50
@ojusto I have just published SPGo 1.4.4 to the VSCode Marketplace which resolves this bug. Please let me know if this resolves the issue for you.

**Comment by ojusto** [comment] 2019-10-10 19:10
Hi @chrishasz , 

I`m already test and all works fine! Thanks soo much !!!

**Comment by chrishasz** [comment] 2019-10-11 23:15
Great, glad this resolved your issue. I'll close this now, but please reach out if you have any other issues or requests.

**Closed by chrishasz** 2019-10-11 23:15 UTC
