### ISSUE TITLE
Server operations stopped working

### ISSUE THREAD

**Issue by MikeKGilmore** [chrishasz/spgo#85] opened 2019-06-05 19:56 UTC
SPGo has been working wonderfully for me since I started using it about 1 month ago but it suddenly stopped performing certain operations, such as publishing, checking out files, etc.

Here is my config:

`{
    "sourceDirectory": "src/yyyyyy",
    "sharePointSiteUrl": "https://xxxxxx.com/xxx/yyyyyy",
    "publishingScope": "Minor",
    "authenticationType": "NTLM",
    "storeCredentials": true,
    "remoteFolders": [
        "/SiteAssets/**/*",
        "/SitePages/**/*"
    ]
}`

I can populate my workspace just fine, but operations involving writes to the server have stopped working.  SPGo does not provide any output indicating the problem.  This is an on-prem SP2013 farm.

SPGo:  1.3.5
VSCode x64: 1.35.0

Thanks in advance!

**Comment by chrishasz** [comment] 2019-06-11 18:08
Hello @MikeKGilmore -

Moving our Email conversation to Github so that this issue resolution will be available to other users. I was able to reproduce and resolve your issue - it turns out that your entry for `sourceDirectory` is malformed in windows. Please change the `sourceDirectory your spgo.json file to use the windows slash, e.g.:

``` json
{ 
    "sourceDirectory": "src\\yyyyyy", 
    "sharePointSiteUrl": "https://xxxxxx.com/xxx/yyyyyy", 
    "publishingScope": "Minor", 
    "authenticationType": "NTLM", 
    "storeCredentials": true, 
    "remoteFolders": [
        "/SiteAssets/**/*", 
        "/SitePages/**/*" 
    ] 
}
```

I will add a feature to the backlog to format the source directory property to the correct path separator for each OS.

Please let me know if this resoves your issue, and I'll close this issue.

Thanks,
Chris

**Comment by MikeKGilmore** [comment] 2019-06-11 20:04
This works great, thank you very much!

**Closed** 2019-06-12 16:03 UTC
