### ISSUE TITLE
Error when publishing file: "input.resume is not a function"

### ISSUE THREAD

**Issue by efernandes1986** [chrishasz/spgo#74] opened 2019-02-07 18:19 UTC
Today I updated my Visual Studio Code to version 1.31.0 and after that SPGo Extension stopped publishing files. When I try to publish a file in my SP 2013 On Premise environment, VSCode outputs "input.resume is not a function" error.

I tried repopulating the folder, resetting credentials, but didn't work out. I'll downgrade my VSCode release to temporarily solve this.

Update: The downgrade of VSCode version solved the problem.

**Comment by lennertcc** [comment] 2019-02-11 15:24
I have the same issue with Code 1.31.0, but downgrading to 1.30.x or 1.29.x did not solve the problem.

I'm connecting to SP2019 on-prem with NTLM.

**Comment by efernandes1986** [comment] 2019-02-11 16:52
Did you confirm you're with the downgraded version of VSCode? I'm asking because I downgraded it but then automatically VSCode updated again to the newest version, so SPGo extension stopped working.

I had to downgrade VCode once again, but this time I ran and disabled automatic updates in File > Preferences > Settings > Application > Update, and then change Channel to "none".

Downgrading did the trick for me.

**Comment by sg-chrishasz** [comment] 2019-02-12 07:14
@efernandes1986 Thanks for the tip to prevent automatic updates!

I believe this is an issue specifically between VSCode 1.31 and SharePoint sites secured with NTLM. I'm still working on diagnosing the root cause. Please see https://github.com/readysitego/spgo/issues/73 for more details.

**Comment by lennertcc** [comment] 2019-02-12 10:44
@efernandes1986  Thanks for the tip, I verified I did test with 1.30.2, see screenshot.

@sg-chrishasz Difference with other reports is my SharePoint on-prem version **2019**. It may well be another root cause of the same error. Thanks for working on it!

![image](https://user-images.githubusercontent.com/4930747/52629950-2bcb0c00-2ebb-11e9-89aa-30a4b2ed5df8.png)

**Comment by lennertcc** [comment] 2019-02-12 13:21
Another finding that I had today is a Windows Security Thread Protection message related to the SPGO extension. Allowing the script did not solve the problem however.

![image](https://user-images.githubusercontent.com/4930747/52638033-44462100-2ed1-11e9-9089-b882a6841804.png)

**Comment by sg-chrishasz** [comment] 2019-02-12 23:11
All- can you review the workaround posted [here](https://github.com/readysitego/spgo/issues/73#issuecomment-462961401) and let me know if this works for you all?

**Comment by sg-chrishasz** [comment] 2019-02-12 23:37
@lennertcc - unfortunately the [event-stream npm package](https://code.visualstudio.com/blogs/2018/11/26/event-stream), in use by one of the VSCode core libraries, was hijacked by bad actors. SPGo 1.3.3 had a dependency on this VSCode library. 

You should make sure to update to the SPGo version 1.3.4+. SPGo was updated within 24 hours of the initial issue being reported and all currently available builds are safe.

**Comment by lennertcc** [comment] 2019-02-13 09:48
@sg-chrishasz Today the extension was updated to 1.3.4. 

> All- can you review the workaround posted [here](https://github.com/readysitego/spgo/issues/73#issuecomment-462961401) and let me know if this works for you all?

Sorry, not working for me. When I remove the setting "authenticationType": "NTLM" the error does not show, but the process hangs on the first library that is not empty.

`{
    "sourceDirectory": "src",
    "sharePointSiteUrl": "https://xxxx",
    "publishingScope": "SaveOnly",
    "remoteFolders": [
        "/SiteAssets/**/*.*",
        "/Style%20Library/**/*.*"
    ]
}`

`SPGo enabled.
Starting File Synchronization...
Successfully downloaded 0 files to: src/SiteAssets
`

**Comment by s-KaiNet** [comment] 2019-02-13 10:01
@sg-chrishasz  I've never seen this issue when playing with NTLM bug, for me it looks like they are not related.

**Comment by efernandes1986** [comment] 2019-02-13 10:53
Guys, my SPGo extension also updated to 1.3.4... Tried updating my VSCode to the latest version and now it's working perfectly. Thank you all.

About the authenticationType, I don't use this line in my settings file and it does work well. See screenshot bellow:

![image](https://user-images.githubusercontent.com/1523326/52706513-bd468680-2f6c-11e9-8e47-0965de7916ec.png)

@lennertcc maybe it's really because of SP2019, mine is 2013.

**Comment by sg-chrishasz** [comment] 2019-02-14 00:53
Hello @lennertcc - I think I know what your issue is. Can you replace the '%20' with a normal space in the `Site%20Assets` remote folder? Dumb error on my part, but I'm not checking for pre-escaped characters and so this will cause your download to fail. I'll fix this for the next release.

@lennertcc and @efernandes1986- I would not recommend removing the `authenticationType` node from your `spgo.json` file. If you do that, SPGo and `node-sp-auth` will attempt to figure out what type of authentication you are using, but you could introduce unknown errors since I add custom auth headers to certain authentication mechanisms, including NTLM, based on `authenticationType`. You can either manually add the property back, or rerun the [Configure Workspace](https://docs.sitego.co/spgo/commands/configure-workspace) command.

**Comment by chrishasz** [comment] 2019-07-05 17:35
Closing this issue- Both the NTLM authentication issue, and the HTML escaping issue have been resolved.

**Closed by chrishasz** 2019-07-05 17:35 UTC
